[tool.poetry]
name = "investment-funnel"
version = "0.0.0"
description = "Open-source testing and benchmarking plaform for asset allocation."
authors = ["Petr Vanek"]
readme = "README.md"
repository = "https://github.com/VanekPetr/investment-funnel"
homepage = "https://investment-funnel.algostrata.com"
packages = [{include = "funnel"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
pandas = "2.2.3"
#pandas-datareader = "0.10.0"
dash = "2.18.2"
dash-bootstrap-components = "1.6.0"
plotly = "5.24.1"
#plotly-express = "0.4.1"
python-dateutil = "2.9.0.post0"
#pulp = "2.9.0"
numpy = "2.2.0"
networkx = "3.4.2"
matplotlib = "3.10.0"
scikit-learn = "1.6.0"
scipy = "1.14.1"
pyarrow = "18.1.0"
yfinance = "0.2.50"
loguru = "0.7.3"
#joblib = "1.4.0"
gunicorn = "23.0.0"
python-dotenv = "1.0.1"
cvxpy-base = "1.6.0"
clarabel = "0.9.0"
#arch = "7.2.0"
#pydantic = "2.10.2"
pydantic-settings = "2.7.0"
tqdm = "4.67.1"
#pre-commit = "4.0.1"
flask = "*"
#gams = "*"
requests = "*"

[tool.poetry.group.test.dependencies]
ecos ="*"
pytest = "*"
pytest-cov = "*"
pre-commit = "*"

[build-system]
requires = ["poetry>=1.7.1"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = ["E", "F", "I"]
line-length = 120
target-version = "py310"
exclude = [
    "*__init__.py"
]

[tool.poetry.scripts]
funnel = "funnel.app:main"

[tool.deptry.per_rule_ignores]
DEP001 = ["gams"]
DEP002 = ["clarabel","pyarrow","cvxpy-base","gunicorn"]
