# Run pre-commit on all files in the repository
name: pre-commit

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
      with:
          extra_args: '--verbose --all-files'

  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cvxgrp/.github/actions/deptry@main
        with:
          source-folder: 'funnel'
